name: "cd"

on:
    workflow_run:
      workflows: ["ci"]
      types:
        - completed

jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
          - uses: actions/checkout@v2

          - name: Set up Google SDK
            uses: google-github-actions/setup-gcloud@master
            with:
                project_id: liatrio-exercise-02
                service_account_key: ${{ secrets.GCP_SA_KEY }}
                export_default_credentials: true
            
          - name: Configure Docker for GCP
            run: gcloud auth configure-docker

          - name: Pull Docker Image
            run: docker pull ${{ secrets.DOCKER_ID }}/liatrio-exercise
          
          - name: Tag Image
            run: docker tag ${{ secrets.DOCKER_ID }}/liatrio-exercise gcr.io/liatrio-exercise-02/${{ secrets.DOCKER_ID }}/liatrio-exercise

          - name: Deploy
            run: gcloud run deploy amdavid --image=gcr.io/liatrio-exercise-02/${{ secrets.DOCKER_ID }}/liatrio-exercise --port=80 --region=us-west2 --platform=managed
