name: "cd"
# Trigger workflow on ci success
on:
    workflow_run:
      workflows: ["ci"]
      types:
        - completed

jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
          - uses: actions/checkout@v2
          # Init gcloud so we can deploy in future steps
          - name: Set up Google SDK
            uses: google-github-actions/setup-gcloud@v0
            with:
                project_id: liatrio-exercise-02
                service_account_key: ${{ secrets.GCP_SA_KEY }}
                export_default_credentials: true
          # Configure docker so we can pull image
          - name: Configure Docker for GCP
            run: gcloud auth configure-docker

          - name: Pull Docker Image
            run: docker pull ${{ secrets.DOCKER_ID }}/liatrio-exercise:latest
          
          - name: Deploy
            run: gcloud run deploy ${{ secrets.DOCKER_ID }} --image=${{ secrets.DOCKER_ID }}/liatrio-exercise:latest --port=80 --region=us-west2 --platform=managed
