name: ci

on:
    push:
        branches:
            - "main"

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            -
                name: Run Tests
                uses: liatrio/github-actions/apprentice-action@master
            -
                name: Checkout
                uses: actions/checkout@v4 # Checkout repository so workflow can access it
            -
                name: Login to Docker Hub
                uses: docker/login-action@v3 # Login and authenticate to Docker Hub
                with:
                    username: ${{ secrets.DOCKER_ID }}
                    password: ${{ secrets.DOCKER_PAT }}
            -
                name: Init Docker Builder # Initialize builder
                uses: docker/setup-buildx-action@v3
            -
                name: Build and Push to Docker Hub
                uses: docker/build-push-action@v5
                with:
                    context: .
                    file: ./Dockerfile
                    push: true
                    tags: ${{ secrets.DOCKER_ID }}/liatrio-exercise:latest # Rename image
